from flask import Flask,render_template,request
import pickle

app=Flask(__name__)
model=pickle.load(open('model.pkl','rb'))
@app.route('/')
def home():
    return render_template('pumphome1.html')
@app.route('/predict',methods=['POST'])
def predict():
   import pdb; pdb.set_trace()
   sensor_00=float(request.form['Sensor_00'])
   sensor_01=float(request.form['Sensor_01'])
   sensor_02=float(request.form['Sensor_02'])
   sensor_03=float(request.form['Sensor_03'])
   sensor_04=float(request.form['Sensor_04'])
   sensor_05=float(request.form['Sensor_05'])
   sensor_06=float(request.form['Sensor_06'])
   sensor_07=float(request.form['Sensor_07'])
   sensor_08=float(request.form['Sensor_08'])
   sensor_09=float(request.form['Sensor_09'])
   sensor_10=float(request.form['Sensor_10'])
   sensor_11=float(request.form['Sensor_11'])
   sensor_12=float(request.form['Sensor_12'])
   sensor_13=float(request.form['Sensor_13'])
   sensor_14=float(request.form['Sensor_14'])
   sensor_16=float(request.form['Sensor_16'])
   sensor_17=float(request.form['Sensor_17'])
   sensor_18=float(request.form['Sensor_18'])
   sensor_19=float(request.form['Sensor_19'])
   sensor_20=float(request.form['Sensor_20'])
   sensor_21=float(request.form['Sensor_21'])
   sensor_22=float(request.form['Sensor_22'])
   sensor_23=float(request.form['Sensor_23'])
   sensor_24=float(request.form['Sensor_24'])
   sensor_25=float(request.form['Sensor_25'])
   sensor_26=float(request.form['Sensor_26'])
   sensor_27=float(request.form['Sensor_27'])
   sensor_28=float(request.form['Sensor_28'])
   sensor_29=float(request.form['Sensor_29'])
   sensor_30=float(request.form['Sensor_30'])
   sensor_31=float(request.form['Sensor_31'])
   sensor_32=float(request.form['Sensor_32'])
   sensor_33=float(request.form['Sensor_33'])
   sensor_34=float(request.form['Sensor_34'])
   sensor_35=float(request.form['Sensor_35'])
   sensor_36=float(request.form['Sensor_36'])
   sensor_37=float(request.form['Sensor_37'])
   sensor_38=float(request.form['Sensor_38'])
   sensor_39=float(request.form['Sensor_39'])
   sensor_40=float(request.form['Sensor_40'])
   sensor_41=float(request.form['Sensor_41'])
   sensor_42=float(request.form['Sensor_42'])
   sensor_43=float(request.form['Sensor_43'])
   sensor_44=float(request.form['Sensor_44'])
   sensor_45=float(request.form['Sensor_45'])
   sensor_46=float(request.form['Sensor_46'])
   sensor_47=float(request.form['Sensor_47'])
   sensor_48=float(request.form['Sensor_48'])
   sensor_49=float(request.form['Sensor_49'])
   sensor_50=float(request.form['Sensor_50'])
   sensor_51=float(request.form['Sensor_51'])

   output=model.predict([[sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,sensor_09,sensor_10,sensor_11,sensor_12,sensor_13,sensor_14,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,sensor_22,sensor_23,sensor_24,sensor_25,sensor_26,sensor_27,sensor_28,sensor_29,sensor_30,sensor_31,sensor_32,sensor_33,sensor_34,sensor_35,sensor_36,sensor_37,sensor_38,sensor_39,sensor_40,sensor_41,sensor_42,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51]])[0]



   return render_template ('pumpresult.html',prediction_text="Pump Sensor is {}".format(output))
if __name__=='__main__':
    app.run(port=5000)